*************************************************************************;
* import_nhanes_data.sas                                      			*;
*************************************************************************;

options nocenter nodate nonumber pagesize=max linesize=150;

* Define paths to Demographic (DEMO) data ;
filename demo url 'https://wwwn.cdc.gov/nchs/nhanes/1999-2000/demo.xpt'; libname demo xport;
filename demo_b url 'https://wwwn.cdc.gov/nchs/nhanes/2001-2002/demo_b.xpt'; libname demo_b xport;
filename demo_c url 'https://wwwn.cdc.gov/nchs/nhanes/2003-2004/demo_c.xpt'; libname demo_c xport;
filename demo_d url 'https://wwwn.cdc.gov/nchs/nhanes/2005-2006/demo_d.xpt'; libname demo_d xport;
filename demo_e url 'https://wwwn.cdc.gov/nchs/nhanes/2007-2008/demo_e.xpt'; libname demo_e xport;
filename demo_f url 'https://wwwn.cdc.gov/nchs/nhanes/2009-2010/demo_f.xpt'; libname demo_f xport;
filename demo_g url 'https://wwwn.cdc.gov/nchs/nhanes/2011-2012/demo_g.xpt'; libname demo_g xport;
filename demo_h url 'https://wwwn.cdc.gov/nchs/nhanes/2013-2014/demo_h.xpt'; libname demo_h xport;
filename demo_i url 'https://wwwn.cdc.gov/nchs/nhanes/2015-2016/demo_i.xpt'; libname demo_i xport;
filename demo_j url 'https://wwwn.cdc.gov/nchs/nhanes/2017-2018/demo_j.xpt'; libname demo_j xport;

* Define paths to the alcohol use (ALQ) data ;
filename alq url 'https://wwwn.cdc.gov/nchs/nhanes/1999-2000/alq.xpt'; libname alq xport;
filename alq_b url 'https://wwwn.cdc.gov/nchs/nhanes/2001-2002/alq_b.xpt'; libname alq_b xport;
filename alq_c url 'https://wwwn.cdc.gov/nchs/nhanes/2003-2004/alq_c.xpt'; libname alq_c xport;
filename alq_d url 'https://wwwn.cdc.gov/nchs/nhanes/2005-2006/alq_d.xpt'; libname alq_d xport;
filename alq_e url 'https://wwwn.cdc.gov/nchs/nhanes/2007-2008/alq_e.xpt'; libname alq_e xport;
filename alq_f url 'https://wwwn.cdc.gov/nchs/nhanes/2009-2010/alq_f.xpt'; libname alq_f xport;
filename alq_g url 'https://wwwn.cdc.gov/nchs/nhanes/2011-2012/alq_g.xpt'; libname alq_g xport;
filename alq_h url 'https://wwwn.cdc.gov/nchs/nhanes/2013-2014/alq_h.xpt'; libname alq_h xport;
filename alq_i url 'https://wwwn.cdc.gov/nchs/nhanes/2015-2016/alq_i.xpt'; libname alq_i xport;
filename alq_j url 'https://wwwn.cdc.gov/nchs/nhanes/2017-2018/alq_j.xpt'; libname alq_j xport;

* Define paths to audiometry (AUQ) data (note: file for 2013-2014 is missing) ;
filename auq url 'https://wwwn.cdc.gov/nchs/nhanes/1999-2000/auq.xpt'; libname auq xport;
filename auq_b url 'https://wwwn.cdc.gov/nchs/nhanes/2001-2002/auq_b.xpt'; libname auq_b xport ;
filename auq_c url 'https://wwwn.cdc.gov/nchs/nhanes/2003-2004/auq_c.xpt'; libname auq_c xport ;
filename auq_d url 'https://wwwn.cdc.gov/nchs/nhanes/2005-2006/auq_d.xpt'; libname auq_d xport ;
filename auq_e url 'https://wwwn.cdc.gov/nchs/nhanes/2007-2008/auq_e.xpt'; libname auq_e xport ;
filename auq_f url 'https://wwwn.cdc.gov/nchs/nhanes/2009-2010/auq_f.xpt'; libname auq_f xport ;
filename auq_g url 'https://wwwn.cdc.gov/nchs/nhanes/2011-2012/auq_g.xpt'; libname auq_g xport ;
/*filename auq_h url 'https://wwwn.cdc.gov/nchs/nhanes/2013-2014/auq_h.xpt'; libname auq_h xport ;*/
filename auq_i url 'https://wwwn.cdc.gov/nchs/nhanes/2015-2016/auq_i.xpt'; libname auq_i xport ;
filename auq_j url 'https://wwwn.cdc.gov/nchs/nhanes/2017-2018/auq_j.xpt'; libname auq_j xport ;

* Define paths to Blood Pressure (BPX) examination data ;
filename bpx url 'https://wwwn.cdc.gov/nchs/nhanes/1999-2000/bpx.xpt'; libname bpx xport;
filename bpx_b url 'https://wwwn.cdc.gov/nchs/nhanes/2001-2002/bpx_b.xpt'; libname bpx_b xport;
filename bpx_c url 'https://wwwn.cdc.gov/nchs/nhanes/2003-2004/bpx_c.xpt'; libname bpx_c xport;
filename bpx_d url 'https://wwwn.cdc.gov/nchs/nhanes/2005-2006/bpx_d.xpt'; libname bpx_d xport;
filename bpx_e url 'https://wwwn.cdc.gov/nchs/nhanes/2007-2008/bpx_e.xpt'; libname bpx_e xport;
filename bpx_f url 'https://wwwn.cdc.gov/nchs/nhanes/2009-2010/bpx_f.xpt'; libname bpx_f xport;
filename bpx_g url 'https://wwwn.cdc.gov/nchs/nhanes/2011-2012/bpx_g.xpt'; libname bpx_g xport;
filename bpx_h url 'https://wwwn.cdc.gov/nchs/nhanes/2013-2014/bpx_h.xpt'; libname bpx_h xport;
filename bpx_i url 'https://wwwn.cdc.gov/nchs/nhanes/2015-2016/bpx_i.xpt'; libname bpx_i xport;
filename bpx_j url 'https://wwwn.cdc.gov/nchs/nhanes/2017-2018/bpx_j.xpt'; libname bpx_j xport;

* Define paths to Diabetes (DIQ) self-report data ;
filename diq url 'https://wwwn.cdc.gov/nchs/nhanes/1999-2000/diq.xpt'; libname diq xport;
filename diq_b url 'https://wwwn.cdc.gov/nchs/nhanes/2001-2002/diq_b.xpt'; libname diq_b xport;
filename diq_c url 'https://wwwn.cdc.gov/nchs/nhanes/2003-2004/diq_c.xpt'; libname diq_c xport;
filename diq_d url 'https://wwwn.cdc.gov/nchs/nhanes/2005-2006/diq_d.xpt'; libname diq_d xport;
filename diq_e url 'https://wwwn.cdc.gov/nchs/nhanes/2007-2008/diq_e.xpt'; libname diq_e xport;
filename diq_f url 'https://wwwn.cdc.gov/nchs/nhanes/2009-2010/diq_f.xpt'; libname diq_f xport;
filename diq_g url 'https://wwwn.cdc.gov/nchs/nhanes/2011-2012/diq_g.xpt'; libname diq_g xport;
filename diq_h url 'https://wwwn.cdc.gov/nchs/nhanes/2013-2014/diq_h.xpt'; libname diq_h xport;
filename diq_i url 'https://wwwn.cdc.gov/nchs/nhanes/2015-2016/diq_i.xpt'; libname diq_i xport;
filename diq_j url 'https://wwwn.cdc.gov/nchs/nhanes/2017-2018/diq_j.xpt'; libname diq_j xport;

* Define paths to blood glucose lab data ;
filename lab10am url 'https://wwwn.cdc.gov/nchs/nhanes/1999-2000/lab10am.xpt'; libname lab10am xport;
filename l10am_b url 'https://wwwn.cdc.gov/nchs/nhanes/2001-2002/l10am_b.xpt'; libname l10am_b xport;
filename l10am_c url 'https://wwwn.cdc.gov/nchs/nhanes/2003-2004/l10am_c.xpt'; libname l10am_c xport;
filename glu_d url 'https://wwwn.cdc.gov/nchs/nhanes/2005-2006/glu_d.xpt'; libname glu_d xport;
filename glu_e url 'https://wwwn.cdc.gov/nchs/nhanes/2007-2008/glu_e.xpt'; libname glu_e xport;
filename glu_f url 'https://wwwn.cdc.gov/nchs/nhanes/2009-2010/glu_f.xpt'; libname glu_f xport;
filename glu_g url 'https://wwwn.cdc.gov/nchs/nhanes/2011-2012/glu_g.xpt'; libname glu_g xport;
filename glu_h url 'https://wwwn.cdc.gov/nchs/nhanes/2013-2014/glu_h.xpt'; libname glu_h xport;
filename glu_i url 'https://wwwn.cdc.gov/nchs/nhanes/2015-2016/glu_i.xpt'; libname glu_i xport;
filename glu_j url 'https://wwwn.cdc.gov/nchs/nhanes/2017-2018/glu_j.xpt'; libname glu_j xport;

* Define paths to Depression Screener (CIQ & DPQ) data ;
filename ciqmdep url 'https://wwwn.cdc.gov/nchs/nhanes/1999-2000/ciqmdep.xpt'; libname ciqmdep xport;
filename ciqdep_b url 'https://wwwn.cdc.gov/nchs/nhanes/2001-2002/ciqdep_b.xpt'; libname ciqdep_b xport;
filename ciqdep_c url 'https://wwwn.cdc.gov/nchs/nhanes/2003-2004/ciqdep_c.xpt'; libname ciqdep_c xport;
filename dpq_d url 'https://wwwn.cdc.gov/nchs/nhanes/2005-2006/dpq_d.xpt'; libname dpq_d xport;
filename dpq_e url 'https://wwwn.cdc.gov/nchs/nhanes/2007-2008/dpq_e.xpt'; libname dpq_e xport;
filename dpq_f url 'https://wwwn.cdc.gov/nchs/nhanes/2009-2010/dpq_f.xpt'; libname dpq_f xport;
filename dpq_g url 'https://wwwn.cdc.gov/nchs/nhanes/2011-2012/dpq_g.xpt'; libname dpq_g xport;
filename dpq_h url 'https://wwwn.cdc.gov/nchs/nhanes/2013-2014/dpq_h.xpt'; libname dpq_h xport;
filename dpq_i url 'https://wwwn.cdc.gov/nchs/nhanes/2015-2016/dpq_i.xpt'; libname dpq_i xport;
filename dpq_j url 'https://wwwn.cdc.gov/nchs/nhanes/2017-2018/dpq_j.xpt'; libname dpq_j xport;

* Define paths to Smoking (SMQ) data ;
filename smq url 'https://wwwn.cdc.gov/nchs/nhanes/1999-2000/smq.xpt'; libname smq xport;
filename smq_b url 'https://wwwn.cdc.gov/nchs/nhanes/2001-2002/smq_b.xpt'; libname smq_b xport;
filename smq_c url 'https://wwwn.cdc.gov/nchs/nhanes/2003-2004/smq_c.xpt'; libname smq_c xport;
filename smq_d url 'https://wwwn.cdc.gov/nchs/nhanes/2005-2006/smq_d.xpt'; libname smq_d xport;
filename smq_e url 'https://wwwn.cdc.gov/nchs/nhanes/2007-2008/smq_e.xpt'; libname smq_e xport;
filename smq_f url 'https://wwwn.cdc.gov/nchs/nhanes/2009-2010/smq_f.xpt'; libname smq_f xport;
filename smq_g url 'https://wwwn.cdc.gov/nchs/nhanes/2011-2012/smq_g.xpt'; libname smq_g xport;
filename smq_h url 'https://wwwn.cdc.gov/nchs/nhanes/2013-2014/smq_h.xpt'; libname smq_h xport;
filename smq_i url 'https://wwwn.cdc.gov/nchs/nhanes/2015-2016/smq_i.xpt'; libname smq_i xport;
filename smq_j url 'https://wwwn.cdc.gov/nchs/nhanes/2017-2018/smq_j.xpt'; libname smq_j xport;

* Define paths for Social Support (SSQ) data because the items we originally planned to use are not in continuous NHANES;
filename ssq url 'https://wwwn.cdc.gov/nchs/nhanes/1999-2000/ssq.xpt'; libname ssq xport;
filename ssq_b url 'https://wwwn.cdc.gov/nchs/nhanes/2001-2002/ssq_b.xpt'; libname ssq_b xport;
filename ssq_c url 'https://wwwn.cdc.gov/nchs/nhanes/2003-2004/ssq_c.xpt'; libname ssq_c xport;
filename ssq_d url 'https://wwwn.cdc.gov/nchs/nhanes/2005-2006/ssq_d.xpt'; libname ssq_d xport;
filename ssq_e url 'https://wwwn.cdc.gov/nchs/nhanes/2007-2008/ssq_e.xpt'; libname ssq_e xport;

* Define paths for BMI (BMX) data ;
filename bmx url 'https://wwwn.cdc.gov/nchs/nhanes/1999-2000/bmx.xpt'; libname bmx xport;
filename bmx_b url 'https://wwwn.cdc.gov/nchs/nhanes/2001-2002/bmx_b.xpt'; libname bmx_b xport;
filename bmx_c url 'https://wwwn.cdc.gov/nchs/nhanes/2003-2004/bmx_c.xpt'; libname bmx_c xport;
filename bmx_d url 'https://wwwn.cdc.gov/nchs/nhanes/2005-2006/bmx_d.xpt'; libname bmx_d xport;
filename bmx_e url 'https://wwwn.cdc.gov/nchs/nhanes/2007-2008/bmx_e.xpt'; libname bmx_e xport;
filename bmx_f url 'https://wwwn.cdc.gov/nchs/nhanes/2009-2010/bmx_f.xpt'; libname bmx_f xport;
filename bmx_g url 'https://wwwn.cdc.gov/nchs/nhanes/2011-2012/bmx_g.xpt'; libname bmx_g xport;
filename bmx_h url 'https://wwwn.cdc.gov/nchs/nhanes/2013-2014/bmx_h.xpt'; libname bmx_h xport;
filename bmx_i url 'https://wwwn.cdc.gov/nchs/nhanes/2015-2016/bmx_i.xpt'; libname bmx_i xport;
filename bmx_j url 'https://wwwn.cdc.gov/nchs/nhanes/2017-2018/bmx_j.xpt'; libname bmx_j xport;

* Define paths for Physical Activity data ;
filename paq url 'https://wwwn.cdc.gov/nchs/nhanes/1999-2000/paq.xpt'; libname paq xport;
filename paq_b url 'https://wwwn.cdc.gov/nchs/nhanes/2001-2002/paq_b.xpt'; libname paq_b xport;
filename paq_c url 'https://wwwn.cdc.gov/nchs/nhanes/2003-2004/paq_c.xpt'; libname paq_c xport;
filename paq_d url 'https://wwwn.cdc.gov/nchs/nhanes/2005-2006/paq_d.xpt'; libname paq_d xport;
filename paq_e url 'https://wwwn.cdc.gov/nchs/nhanes/2007-2008/paq_e.xpt'; libname paq_e xport;
filename paq_f url 'https://wwwn.cdc.gov/nchs/nhanes/2009-2010/paq_f.xpt'; libname paq_f xport;
filename paq_g url 'https://wwwn.cdc.gov/nchs/nhanes/2011-2012/paq_g.xpt'; libname paq_g xport;
filename paq_h url 'https://wwwn.cdc.gov/nchs/nhanes/2013-2014/paq_h.xpt'; libname paq_h xport;
filename paq_i url 'https://wwwn.cdc.gov/nchs/nhanes/2015-2016/paq_i.xpt'; libname paq_i xport;
filename paq_j url 'https://wwwn.cdc.gov/nchs/nhanes/2017-2018/paq_j.xpt'; libname paq_j xport;

* Location of output files ;
libname nhanes 'd:\nhanes\data' ;

* Read in SAS transport files using a data step and append across survey cycles - Demographic files *;
data demog;
  set 	demo.demo(keep=seqn riagendr ridageyr ridreth1 dmdeduc2 sdmvstra sdmvpsu wtmec2yr);
  year = 1999 ;
run;
data demog_b ;
  set 	demo_b.demo_b(keep=seqn riagendr ridageyr ridreth1 dmdeduc2 sdmvstra sdmvpsu wtmec2yr);
  year = 2001 ;
run;
data demog_c;
  set 	demo_c.demo_c(keep=seqn riagendr ridageyr ridreth1 dmdeduc2 sdmvstra sdmvpsu wtmec2yr);
  year = 2003 ;
run;
data demog_d;
  set 	demo_d.demo_d(keep=seqn riagendr ridageyr ridreth1 dmdeduc2 sdmvstra sdmvpsu wtmec2yr);
  year = 2005 ;
run;
data demog_e;
  set 	demo_e.demo_e(keep=seqn riagendr ridageyr ridreth1 dmdeduc2 sdmvstra sdmvpsu wtmec2yr);
  year = 2007 ;
run;
data demog_f;
  set 	demo_f.demo_f(keep=seqn riagendr ridageyr ridreth1 dmdeduc2 sdmvstra sdmvpsu wtmec2yr);
  year = 2009 ;
run;
data demog_g;
  set 	demo_g.demo_g(keep=seqn riagendr ridageyr ridreth1 dmdeduc2 sdmvstra sdmvpsu wtmec2yr);
  year = 2011 ;
run;
data demog_h;
  set 	demo_h.demo_h(keep=seqn riagendr ridageyr ridreth1 dmdeduc2 sdmvstra sdmvpsu wtmec2yr);
  year = 2013 ;
run;
data demog_i;
  set 	demo_i.demo_i(keep=seqn riagendr ridageyr ridreth1 dmdeduc2 sdmvstra sdmvpsu wtmec2yr);
  year = 2015 ;
run;
data demog_j;
  set 	demo_j.demo_j(keep=seqn riagendr ridageyr ridreth1 dmdeduc2 sdmvstra sdmvpsu wtmec2yr);
  year = 2017 ;
run;
data nhanes.demog ;
	set demog demog_b demog_c demog_d demog_e demog_f demog_g demog_h demog_i demog_j;
	if ridageyr ge 45 ;
	* 31576 observations ;
run ;
* Read in SAS transport files and append  across survey cycles - Alcohol Use files;
data alc;
	set alq.alq(keep=seqn alq130) ;
	year = 1999 ;
run ;
data alc_b;
	set alq_b.alq_b(keep=seqn alq130) ;
	  year = 2001 ;
run ;
data alc_c;
	set alq_c.alq_c(keep=seqn alq130) ;
  year = 2003 ;
run ;
data alc_d;
	set alq_d.alq_d(keep=seqn alq130) ;
  year = 2005 ;
run ;
data alc_e;
	set alq_e.alq_e(keep=seqn alq130) ;
  year = 2007 ;
run ;
data alc_f;
	set alq_f.alq_f(keep=seqn alq130) ;
  year = 2009 ;
run ;
data alc_g;
	set alq_g.alq_g(keep=seqn alq130) ;
  year = 2011 ;
run ;
data alc_h;
	set alq_h.alq_h(keep=seqn alq130) ;
  year = 2013 ;
run ;
data alc_i;
	set alq_i.alq_i(keep=seqn alq130) ;
  year = 2015 ;
run ;
data alc_j;
	set alq_j.alq_j(keep=seqn alq130) ;
  year = 2017 ;
run ;
data nhanes.alcohol ;
	set alc alc_b alc_c alc_d alc_e alc_f alc_g alc_h alc_i alc_j;
	* 53559 observations ;
run ;
* Read in SAS transport files and append  across survey cycles - Audiometry files;
data hear;
	set auq.auq(keep=seqn auq130) ;
	year = 1999 ;
run ;
data hear_b;
	set auq_b.auq_b(keep=seqn auq130) ;
 	year = 2001 ;
run ;
data hear_c;
	set auq_c.auq_c(keep=seqn auq130) ;
  	year = 2003 ;
run ;
* Variable name for general hearing changes in 2005-2006 ;
data hear_d;
	set auq_d.auq_d(keep=seqn auq131) ;
  	year = 2005 ;
run ;
data hear_e;
	set auq_e.auq_e(keep=seqn auq131) ;
	year = 2007 ;
run ;
data hear_f;
	set auq_f.auq_f(keep=seqn auq131) ;
  	year = 2009 ;
run ;
* Variable name for general hearing changes in 2011-2012 ;
data hear_g;
	set auq_g.auq_g(keep=seqn auq054) ;
  	year = 2011 ;
run ;
* Data for 2013-2014 (auq_h) missing from website ;
data hear_i;
	set auq_i.auq_i(keep=seqn auq054) ;
  	year = 2015 ;
run ;
data hear_j;
	set auq_j.auq_j(keep=seqn auq054) ;
  	year = 2017 ;
run ;
data nhanes.hearing ;
	set hear hear_b hear_c hear_d hear_e hear_f hear_g hear_i hear_j;
	* 87041 observations ;
run ;
* Read in SAS transport files and append across survey cycles - Blood Pressure ;
data bp ;
	set bpx.bpx(keep=seqn bpxsar bpxdar) ;
	year = 1999 ;
run ;
data bp_b ;
	set bpx_b.bpx_b(keep=seqn bpxsar bpxdar) ;
	year = 2001 ;
run ;
data bp_c ;
	set bpx_c.bpx_c(keep=seqn bpxsar bpxdar) ;
	year = 2003 ;
run ;
* In 2005, they dropped the average blood pressure reading ;
data bp_d ;
	set bpx_d.bpx_d(keep=seqn bpxsy1 bpxsy2 bpxsy3 bpxsy4 bpxdi1 bpxdi2 bpxdi3 bpxdi4) ;
	year = 2005 ;
run ;
data bp_e ;
	set bpx_e.bpx_e(keep=seqn bpxsy1 bpxsy2 bpxsy3 bpxsy4 bpxdi1 bpxdi2 bpxdi3 bpxdi4) ;
	year = 2007 ;
run ;
data bp_f ;
	set bpx_f.bpx_f(keep=seqn bpxsy1 bpxsy2 bpxsy3 bpxsy4 bpxdi1 bpxdi2 bpxdi3 bpxdi4) ;
	year = 2009 ;
run ;
data bp_g ;
	set bpx_g.bpx_g(keep=seqn bpxsy1 bpxsy2 bpxsy3 bpxsy4 bpxdi1 bpxdi2 bpxdi3 bpxdi4) ;
	year = 2011 ;
run ;
data bp_h ;
	set bpx_h.bpx_h(keep=seqn bpxsy1 bpxsy2 bpxsy3 bpxsy4 bpxdi1 bpxdi2 bpxdi3 bpxdi4) ;
	year = 2013 ;
run ;
data bp_i ;
	set bpx_i.bpx_i(keep=seqn bpxsy1 bpxsy2 bpxsy3 bpxsy4 bpxdi1 bpxdi2 bpxdi3 bpxdi4) ;
	year = 2015 ;
run ;
data bp_j ;
	set bpx_j.bpx_j(keep=seqn bpxsy1 bpxsy2 bpxsy3 bpxsy4 bpxdi1 bpxdi2 bpxdi3 bpxdi4) ;
	year = 2017 ;
run ;
data nhanes.blood_pressure ;
	set bp bp_b bp_c bp_d bp_e bp_f bp_g bp_h bp_i bp_j ;
	* 96766 observations ;
run ;
* Read in SAS transport files and append across survey cycles - Diabetes self-report ;
* Note, data are missing for 2003-2009 and 2015-2017 ;
data dm ;
	set diq.diq(keep=seqn diq010) ;
	year = 1999 ;
run ;
data dm_b ;
	set diq_b.diq_b(keep=seqn diq010) ;
	year = 2001 ;
run ;
data dm_c ;
	set diq_c.diq_c(keep=seqn diq010) ;
	year = 2003 ;
run ;
data dm_d ;
	set diq_d.diq_d(keep=seqn diq010) ;
	year = 2005 ;
run ;
data dm_e ;
	set diq_e.diq_e(keep=seqn diq010) ;
	year = 2007 ;
run ;
data dm_f ;
	set diq_f.diq_f(keep=seqn diq010) ;
	year = 2009 ;
run ;
data dm_g ;
	set diq_g.diq_g(keep=seqn diq010) ;
	year = 2011 ;
run ;
data dm_h ;
	set diq_h.diq_h(keep=seqn diq010) ;
	year = 2013 ;
run ;
data dm_i ;
	set diq_i.diq_i(keep=seqn diq010) ;
	year = 2015 ;
run ;
data dm_j ;
	set diq_j.diq_j(keep=seqn diq010) ;
	year = 2017 ;
run ;
data nhanes.diabetes_self_report ;
	set dm dm_b dm_c dm_d dm_e dm_f dm_g dm_h dm_i dm_j ;
	* 96766 observations ;
run ;
* Read in SAS transport files and append across surve cycles - Blood Plasma Glucose ;
data glucose ;
	set lab10am.lab10am(keep=seqn lbxglu) ;
	year = 1999 ;
run ;
data glucose_b ;
	set l10am_b.l10am_b(keep=seqn lbxglu) ;
	year = 2001 ;
run ;
data glucose_c ;
	set l10am_c.l10am_c(keep=seqn lbxglu) ;
	year = 2003 ;
run ;
data glucose_d ;
	set glu_d.glu_d(keep=seqn lbxglu) ;
	year = 2005 ;
run ;
data glucose_e ;
	set glu_e.glu_e(keep=seqn lbxglu) ;
	year = 2007 ;
run ;
data glucose_f ;
	set glu_f.glu_f(keep=seqn lbxglu) ;
	year = 2009 ;
run ;
data glucose_g ;
	set glu_g.glu_g(keep=seqn lbxglu) ;
	year = 2011 ;
run ;
data glucose_h ;
	set glu_h.glu_h(keep=seqn lbxglu) ;
	year = 2013 ;
run ;
data glucose_i ;
	set glu_i.glu_i(keep=seqn lbxglu) ;
	year = 2015 ;
run ;
data glucose_j ;
	set glu_j.glu_j(keep=seqn lbxglu) ;
	year = 2017 ;
run ;
data nhanes.diabetes_lab ;
	set glucose glucose_b glucose_c glucose_d glucose_e glucose_f glucose_g glucose_h glucose_i glucose_j ;
	* 33332 observations ;
run ;
* Read in SAS transport files and append  across survey cycles - Mental Health - Depression Screener files ;
data dep ;
	set ciqmdep.ciqmdep(keep=seqn ciddscor) ;
	year = 1999 ;
run ;
data dep_b ;
	set ciqdep_b.ciqdep_b(keep=seqn ciddscor) ;
	year = 2001 ;
run ;
data dep_c ;
	set ciqdep_c.ciqdep_c(keep=seqn ciddscor) ;
	year = 2003 ;
run ;
data dep_d ;
	set dpq_d.dpq_d(keep = seqn dpq010--dpq090) ;
	year = 2005 ;
run ;
data dep_e ;
	set dpq_e.dpq_e(keep = seqn dpq010--dpq090) ;
	year = 2007 ;
run ;
data dep_f ;
	set dpq_f.dpq_f(keep = seqn dpq010--dpq090) ;
	year = 2009 ;
run ;
data dep_g ;
	set dpq_g.dpq_g(keep = seqn dpq010--dpq090) ;
	year = 2011 ;
run ;
data dep_h ;
	set dpq_h.dpq_h(keep = seqn dpq010--dpq090) ;
	year = 2013 ;
run ;
data dep_i ;
	set dpq_i.dpq_i(keep = seqn dpq010--dpq090) ;
	year = 2015 ;
run ;
data dep_j ;
	set dpq_j.dpq_j(keep = seqn dpq010--dpq090) ;
	year = 2017 ;
run ;
data nhanes.depression ;
	set dep dep_b dep_c dep_d dep_e dep_f dep_g dep_h dep_i dep_j ;
	* 43052 observations ;
run ;
* Read in SAS transport files and append across survey cycles - Smoking files *;
data smk ;
	set smq.smq(keep=seqn smq020) ;
	year = 1999 ;
run ;
data smk_b ;
	set smq_b.smq_b(keep=seqn smq020) ;
	year = 2001 ;
run ;
data smk_c ;
	set smq_c.smq_c(keep=seqn smq020) ;
	year = 2003 ;
run ;
data smk_d ;
	set smq_d.smq_d(keep=seqn smq020) ;
	year = 2005 ;
run ;
data smk_e ;
	set smq_e.smq_e(keep=seqn smq020) ;
	year = 2007 ;
run ;
data smk_f ;
	set smq_f.smq_f(keep=seqn smq020) ;
	year = 2009 ;
run ;
data smk_g ;
	set smq_g.smq_g(keep=seqn smq020) ;
	year = 2011 ;
run ;
data smk_h ;
	set smq_h.smq_h(keep=seqn smq020) ;
	year = 2013 ;
run ;
data smk_i ;
	set smq_i.smq_i(keep=seqn smq020) ;
	year = 2015 ;
run ;
data smk_j ;
	set smq_j.smq_j(keep=seqn smq020) ;
	year = 2017 ;
run ;
data nhanes.smoking ;
	set smk smk_b smk_c smk_d smk_e smk_f smk_g smk_h smk_i smk_j ;
	* 64874 observations ;
run ;
* Read in SAS transport files and append across survey cycles - Social Support files *;
* Note, data available for 1999-2007 ;
* Age range is 60+;
data soc ;
	set ssq.ssq(keep=seqn ssq010) ;
	year = 1999 ;
run ;
* Variable name changes and age range is 60+ ;
data soc_b ;
	set ssq_b.ssq_b(keep=seqn ssd011) ;
	year = 2001 ;
run ;
* Variable name changes and age range is 40+ ;
data soc_c ;
	set ssq_c.ssq_c(keep=seqn ssq011) ;
	year = 2003 ;
run ;
data soc_d ;
	set ssq_d.ssq_d(keep=seqn ssq011) ;
	year = 2005 ;
run ;
data soc_e ;
	set ssq_e.ssq_e(keep=seqn ssq011) ;
	year = 2007 ;
run ;
data nhanes.soc_support ;
	set soc soc_b soc_c soc_d soc_e ;
	* 14086 observations ;
run ;
* Read in SAS transport files and append across survey cycles - BMI files *;
data bmi ;
	set bmx.bmx(keep=seqn bmxbmi) ;
	year = 1999 ;
run ;
data bmi_b ;
	set bmx_b.bmx_b(keep=seqn bmxbmi) ;
	year = 2001 ;
run ;
data bmi_c ;
	set bmx_c.bmx_c(keep=seqn bmxbmi) ;
	year = 2003 ;
run ;
data bmi_d ;
	set bmx_d.bmx_d(keep=seqn bmxbmi) ;
	year = 2005 ;
run ;
data bmi_e ;
	set bmx_e.bmx_e(keep=seqn bmxbmi) ;
	year = 2007 ;
run ;
data bmi_f ;
	set bmx_f.bmx_f(keep=seqn bmxbmi) ;
	year = 2009 ;
run ;
data bmi_g ;
	set bmx_g.bmx_g(keep=seqn bmxbmi) ;
	year = 2011 ;
run ;
data bmi_h ;
	set bmx_h.bmx_h(keep=seqn bmxbmi) ;
	year = 2013 ;
run ;
data bmi_i ;
	set bmx_i.bmx_i(keep=seqn bmxbmi) ;
	year = 2015 ;
run ;
data bmi_j ;
	set bmx_j.bmx_j(keep=seqn bmxbmi) ;
	year = 2017 ;
run ;
data nhanes.bmi ;
	set bmi bmi_b bmi_c bmi_d bmi_e bmi_f bmi_g bmi_h bmi_i bmi_j ;
	* 96766 observations ;
run ;
* Read in SAS transport files and append across survey cycles - Physical Activity files *;
data phys ;
	set paq.paq(keep=seqn pad320) ;
	year = 1999 ;
run ;
data phys_b ;
	set paq_b.paq_b(keep=seqn pad320) ;
	year = 2001 ;
run ;
data phys_c ;
	set paq_c.paq_c(keep=seqn pad320) ;
	year = 2003 ;
run ;
data phys_d ;
	set paq_d.paq_d(keep=seqn pad320) ;
	year = 2005 ;
run ;
* Variable name changes and values are range of minutes spent in moderate activity ;
data phys_e ;
	set paq_e.paq_e(keep=seqn pad675) ;
	year = 2007 ;
run ;
data phys_f ;
	set paq_f.paq_f(keep=seqn pad675) ;
	year = 2009 ;
run ;
data phys_g ;
	set paq_g.paq_g(keep=seqn pad675) ;
	year = 2011 ;
run ;
data phys_h ;
	set paq_h.paq_h(keep=seqn pad675) ;
	year = 2013 ;
run ;
data phys_i ;
	set paq_i.paq_i(keep=seqn pad675) ;
	year = 2015 ;
run ;
data phys_j ;
	set paq_j.paq_j(keep=seqn pad675) ;
	year = 2017 ;
run ;
data nhanes.phys_activity ;
	set phys phys_b phys_c phys_d phys_e phys_f phys_g phys_h phys_i phys_j ;
	* 90816 observations ;
run ;
* Merge the data together into a single data set ;
data nhanes.nhanes_combined ;
	merge nhanes.demog (in = a) nhanes.alcohol nhanes.blood_pressure nhanes.bmi
	nhanes.depression nhanes.diabetes_lab nhanes.diabetes_self_report
	nhanes.hearing nhanes.phys_activity nhanes.smoking nhanes.soc_support ;
	by seqn year;
	if (a eq 1) ;
	* 31576 observations ;
run ;






